name: API testing automation

on:
  workflow_dispatch:

jobs:
  regression-test-run:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Run API tests 🧪
        uses: cypress-io/github-action@v5
        with:
          start: npm run test
          command: npm run test:api
